name: seaside
version: 0.0.4

homepage: https://github.com/renggli/dart-seaside
description: A web application server framework.

environment:
  sdk: ^3.13.0
dependencies:
  collection: ^1.19.1
  meta: ^1.19.0
  more: ^4.7.0
  shelf: ^1.4.2
dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2
