name: seaside
version: 0.0.3

homepage: https://github.com/renggli/dart-seaside
description: A web application server framework.

environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  more: ^3.3.0
  shelf: ^1.2.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.0
