name: seaside
version: 0.0.4

homepage: https://github.com/renggli/dart-seaside
description: A web application server framework.

environment:
  sdk: ^3.5.0
dependencies:
  collection: ^1.19.0
  meta: ^1.15.0
  more: ^4.3.0
  shelf: ^1.4.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
