name: seaside
description: A web server built using the shelf package.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  collection: ^1.14.0
  meta: ^1.2.0
  more: ^2.6.0
  shelf: ^0.7.0
  shelf_router: ^0.7.0
