name: seaside
version: 0.0.4

homepage: https://github.com/renggli/dart-seaside
description: A web application server framework.

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  collection: ^1.16.0
  meta: ^1.8.0
  more: ^3.8.0
  shelf: ^1.3.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
